// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HmXeHVZfhl3-lVjXrx3jngtGF-CTNTE',
    appId: '1:234910971653:web:a5c9f0f10665d73845a96c',
    messagingSenderId: '234910971653',
    projectId: 'fir-authentication-856df',
    authDomain: 'fir-authentication-856df.firebaseapp.com',
    storageBucket: 'fir-authentication-856df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClb4j3myI9U0tN2MYXB46-nOAf2AM3ctw',
    appId: '1:234910971653:android:d9adaac950110f6245a96c',
    messagingSenderId: '234910971653',
    projectId: 'fir-authentication-856df',
    storageBucket: 'fir-authentication-856df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzsrzrlbQH0DlncWoM3BZ1DTjQOKJuEao',
    appId: '1:234910971653:ios:494c86655749bd8045a96c',
    messagingSenderId: '234910971653',
    projectId: 'fir-authentication-856df',
    storageBucket: 'fir-authentication-856df.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
